apiVersion: v2
appVersion: 0.19.0
description: NATS HTTP Gateway
name: http-gateway
version: 0.1.0
home: http://github.com/synadia-io/helm-charts
maintainers:
- name: Synadia
  url: https://github.com/synadia-io
  email: info@synadia.com
