apiVersion: apps/v1
kind: StatefulSet
metadata:
  {{- include "ins.metadataNamespace" $ | nindent 2 }}
  name: {{ .Values.statefulSet.name }}
  labels:
    {{- include "ins.labels" $ | nindent 4 }}
spec:
  serviceName: {{ .Values.headlessService.name | quote }}
  replicas: {{ .Values.statefulSet.replicas }}
  selector:
    matchLabels:
      {{- include "ins.selectorLabels" $ | nindent 6 }}

  {{- with .Values.statefulSet.updateStrategy }}
  updateStrategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  template:
    {{- with .Values.podTemplate }}
    {{- include "ins.loadMergePatch" (merge (dict "file" "statefulset/pod-template.yaml" "ctx" $) .) | nindent 4 }}
    {{- end }}

  {{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: data
      labels:
        {{- include "ins.labels" $ | nindent 8 }}
    spec:
      accessModes:
        {{- toYaml .Values.persistence.accessModes | nindent 6 }}
      resources:
        requests:
          storage: {{ .Values.persistence.size | quote }}
      {{- with .Values.persistence.storageClassName }}
      storageClassName: {{ . | quote }}
      {{- end }}
  {{- end }}
