apiVersion: v2
name: insights
description: Real-time observability for NATS infrastructure
type: application
version: "0.1.2"
appVersion: "0.1.10"
home: https://docs.synadia.com/insights
sources:
  - https://github.com/synadia-io/helm-charts
maintainers:
  - name: Synadia
    url: https://github.com/synadia-io
