apiVersion: v1
kind: Secret
metadata:
  {{- include "nce.metadataNamespace" $ | nindent 2 }}
  name: {{ .Values.configSecret.name }}
  labels:
    {{- include "nce.labels" $ | nindent 4 }}
type: Opaque
stringData:
  config.json: |
    {{- include "nce.config" $ | nindent 4 }}
