apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: {{ .nceRoleNamespace | quote }}
  name: {{ .Values.serviceAccount.name }}-rolebinding
  labels:
    {{- include "nce.labels" $ | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.name }}
    namespace: {{ include "nce.namespace" $ | trim | quote }}
roleRef:
  kind: Role
  name: {{ .Values.serviceAccount.name }}-role
  apiGroup: rbac.authorization.k8s.io
