apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.serviceAccount.name }}-role
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["create", "read", "get", "list", "watch", "update", "patch", "delete"]
- apiGroups: ["", "apps", "extensions", "batch", "rbac.authorization.k8s.io", "networking.k8s.io", "*"]
  resources: ["*"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
