{{- include "nce.defaultValues" . }}
{{- if .Values.serviceAccount.enabled }}
{{- range $ns := include "nce.nexletNamespaces" $ | fromJsonArray }}
{{- $_ := set $ "nceRoleNamespace" $ns }}
---
{{ include "nce.loadMergePatch" (merge (dict "file" "service-account-rolebinding.yaml" "ctx" $) $.Values.serviceAccount) }}
{{- end }}
{{- end }}
