{{- include "nce.defaultValues" . }}
{{- with .Values.serviceAccount }}
{{- if .enabled }}
{{- include "nce.loadMergePatch" (merge (dict "file" "service-account-role.yaml" "ctx" $) .) }}
{{- end }}
{{- end }}
