{{- include "nce.defaultValues" . }}
{{- if .Values.workloadServiceAccount.enabled }}
{{- range $ns := include "nce.nexletNamespaces" $ | fromJsonArray }}
{{- $_ := set $ "nceRoleNamespace" $ns }}
---
{{ include "nce.loadMergePatch" (merge (dict "file" "workload-service-account.yaml" "ctx" $) $.Values.workloadServiceAccount) }}
{{- end }}
{{- end }}
