{{- include "ins.defaultValues" . }}
{{- if include "ins.hasConfigSecret" . }}
{{- with .Values.configSecret }}
{{- include "ins.loadMergePatch" (merge (dict "file" "config-secret.yaml" "ctx" $) .) }}
{{- end }}
{{- end }}
