{{- include "ins.defaultValues" . }}
{{- if or .Values.config.sys.creds .Values.config.license.token .Values.config.web.sessionSeed }}
{{- with .Values.configSecret }}
{{- include "ins.loadMergePatch" (merge (dict "file" "config-secret.yaml" "ctx" $) .) }}
{{- end }}
{{- end }}
