{{- include "ins.defaultValues" . }}
{{- with .Values.imagePullSecret }}
{{- if .enabled }}
{{- include "ins.loadMergePatch" (merge (dict "file" "image-pull-secret.yaml" "ctx" $) .) }}
{{- end }}
{{- end }}
