{{- if not .Values.configSecret.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "insights.configSecretName" . }}
  labels:
    {{- include "insights.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.configSecret.key | quote }}: |
    {{- toYaml .Values.config | nindent 4 }}
{{- end }}
