{{- include "sd.defaultValues" . }}
{{- with .Values.serviceAccount }}
{{- if .enabled }}
{{- $clusterRoleName := printf "%s-cluster-role" .name }}
{{- $existingClusterRole := lookup "rbac.authorization.k8s.io/v1" "ClusterRole" "" $clusterRoleName }}
{{- if not $existingClusterRole }}
{{- include "sd.loadMergePatch" (merge (dict "file" "service-account-cluster-role.yaml" "ctx" $) .) }}
{{- end }}
{{- end }}
{{- end }}