apiVersion: v1
kind: Secret
metadata:
  {{- include "ins.metadataNamespace" $ | nindent 2 }}
  name: {{ .Values.configSecret.name }}
  labels:
    {{- include "ins.labels" $ | nindent 4 }}
type: Opaque
stringData:
  {{- with .Values.config.sys.creds }}
  sys.creds: |
    {{- . | nindent 4 }}
  {{- end }}
  {{- with .Values.config.license.token }}
  license.jwt: {{ . | quote }}
  {{- end }}
  {{- with .Values.config.web.sessionSeed }}
  session-seed: {{ . | quote }}
  {{- end }}
