{{- with .Values.headlessService }}
apiVersion: v1
kind: Service
metadata:
  {{- include "ins.metadataNamespace" $ | nindent 2 }}
  name: {{ .name }}
  labels:
    {{- include "ins.labels" $ | nindent 4 }}
spec:
  clusterIP: None
  selector:
    {{- include "ins.selectorLabels" $ | nindent 4 }}
  ports:
  - name: http
    port: {{ $.Values.config.web.port }}
    targetPort: http
  - name: nats
    port: {{ $.Values.config.sink.port }}
    targetPort: nats
{{- end }}
