apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  {{- include "ins.metadataNamespace" $ | nindent 2 }}
  name: {{ .Values.podDisruptionBudget.name }}
  labels:
    {{- include "ins.labels" $ | nindent 4 }}
spec:
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  selector:
    matchLabels:
      {{- include "ins.selectorLabels" $ | nindent 6 }}
