{{- with .Values.podMonitor }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  {{- include "ins.metadataNamespace" $ | nindent 2 }}
  name: {{ .name }}
  labels:
    {{- include "ins.labels" $ | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "ins.selectorLabels" $ | nindent 6 }}
  podMetricsEndpoints:
  - port: metrics
    path: {{ .path | default "/metrics" | quote }}
    {{- with .interval }}
    interval: {{ . | quote }}
    {{- end }}
{{- end }}
