apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "sd.clusterRoleName" $ }}
rules:
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingressclasses"]
    verbs: ["get", "list"]

  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list"]

  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list"]

  - apiGroups: []
    resources: []
    verbs: ["get"]
    nonResourceURLs: ["/version"]

  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["clusterroles", "clusterrolebindings"]
    resourceNames:
      - {{ include "sd.clusterRoleName" $ }}
      - {{ include "sd.clusterRoleBindingName" $ }}
    verbs: ["get", "patch"]
