apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ printf "%s-cluster-role" .Values.serviceAccount.name }}
rules:
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingressclasses"]
    verbs: ["get", "list"]

  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list"]

  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list"]

  - apiGroups: []
    resources: []
    verbs: ["get"]
    nonResourceURLs: ["/version"]