apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ printf "%s-role" .Values.serviceAccount.name }}
rules:
  - apiGroups: ["", "apps", "extensions", "batch", "rbac.authorization.k8s.io", "networking.k8s.io", "*"]
    resources: ["*"]
    verbs: ["get", "read", "list", "watch", "create", "update", "patch", "delete"]
