apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ printf "%s-%s-cluster-rolebinding" (include "sd.namespace" $) .Values.serviceAccount.name }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.name }}
    namespace: {{ include "sd.namespace" $ }}
roleRef:
  kind: ClusterRole
  name: {{ printf "%s-cluster-role" .Values.serviceAccount.name }}
  apiGroup: rbac.authorization.k8s.io
