apiVersion: v1
kind: Secret
metadata:
  {{- include "sd.metadataNamespace" $ | nindent 2 }}
  name: {{ .Values.tokenSecret.name }}
  labels:
    {{- include "sd.labels" $ | nindent 4 }}
type: Opaque
stringData:
  token: {{ .Values.config.token }}
