metadata:
  labels:
    {{- include "nce.labels" $ | nindent 4 }}
  annotations:
spec:
  containers:
  # nex-ce
  {{- with .Values.container }}
  - {{ include "nce.loadMergePatch" (merge (dict "file" "deployment/nex-ce-container.yaml" "ctx" $) .) | nindent 4 }}
  {{- end }}

  # don't need service env vars
  enableServiceLinks: false

  {{- with .Values.global.image.pullSecretNames }}
  imagePullSecrets:
  {{- range . }}
  - name: {{ . | quote }}
  {{- end }}
  {{- end }}

  {{- with .Values.serviceAccount }}
  {{- if .enabled }}
  serviceAccountName: {{ .name | quote }}
  {{- end }}
  {{- end }}

  volumes:
   # tlsCA
  {{- include "nce.tlsCAVolume" $ | nindent 2 }}
  # secrets
  {{- range (include "nce.secretNames" $ | fromJson).secretNames }}
  - name: {{ .name | quote }}
    secret:
      secretName: {{ .secretName | quote }}
  {{- end }}
  # configSecret
  - name: config
    secret:
      secretName: {{ .Values.configSecret.name | default (printf "%s-config" (include "nce.fullname" $)) | quote }}

  {{- with .Values.podTemplate.topologySpreadConstraints }}
  topologySpreadConstraints:
  {{- range $k, $v := . }}
  - {{ merge (dict "topologyKey" $k "labelSelector" (dict "matchLabels" (include "nce.selectorLabels" $ | fromYaml)) "matchLabelKeys" (list "pod-template-hash")) $v | toYaml | nindent 4 }}
  {{- end }}
  {{- end}}
