name: http-gateway
{{ include "nhg.image" (merge (pick .Values "global") .Values.container.image) }}

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL

args:
- run
{{- with .Values.config }}
- --tokens-bucket={{ .tokensBucket }}
- --provider-creds={{ .creds.dir }}/{{ .creds.key }}
{{- with .tls.cert }}
{{- if and (and .enabled .secretName) (and .cert .key) }}
- --certificate={{ .dir }}/{{ .cert }}
- --key={{ .dir }}/{{ .key }}
{{- end }}
{{- end }}
{{- if .advertise }}
- --advertise={{ .advertise }}
{{- end }}
{{- if .tls.enabled }}
- --user-port={{ .httpsPort }}
{{- else }}
- --user-port={{ .httpPort }}
{{- end }}
- {{ .url }}
{{- end }}

{{- with .Values.container.env }}
{{- include "nhg.env" . }}
{{- end }}

ports:
- name: http
  containerPort: {{ .Values.config.httpPort }}
{{- if .Values.config.tls.enabled }}
- name: https
  containerPort: {{ .Values.config.httpsPort }}
{{- end }}

volumeMounts:
# tlsCA
{{- include "nhg.tlsCAVolumeMount" $ }}
# secrets
{{- range (include "nhg.secretNames" $ | fromJson).secretNames }}
- name: {{ .name | quote }}
  mountPath: {{ .dir | quote }}
{{- end }}
