apiVersion: v2
appVersion: 1.0.4-rc3
description: Synadia Connect Node
name: connect-node
version: 0.1.1
home: http://github.com/synadia-io/helm-charts
maintainers:
- name: Synadia
  url: https://github.com/synadia-io
  email: info@synadia.com
