apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  labels:
    {{- include "sd.labels" $ | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "sd.selectorLabels" $ | nindent 6 }}

  replicas: {{ .Values.deployment.replicas }}

  template:
    {{- with .Values.podTemplate }}
    {{- include "sd.loadMergePatch" (merge (dict "file" "deployment/pod-template.yaml" "ctx" $) .) | nindent 4 }}
    {{- end }}
