apiVersion: v2
appVersion: 0.1.0-rc.0
description: Synadia Deploy
name: synadia-deploy
version: 0.1.1
home: http://github.com/synadia-io/helm-charts
maintainers:
- name: Synadia
  url: https://github.com/synadia-io
  email: info@synadia.com
